### ISSUE TITLE
Where do I add the extension repo activation code?

### ISSUE THREAD

**Issue by aadilayub** [kylejbrk/standard-notes-open-extended#10] opened 2021-11-19 08:12 UTC
Sorry if this a dumb question. But there doesn't seem to be any field/input where I can add a third party extension repo in the latest version of Standard Notes

 ![image](https://user-images.githubusercontent.com/31581044/142588009-cf472c26-c8a9-48c5-ab23-9c9164e9bbe3.png)

![image](https://user-images.githubusercontent.com/31581044/142588164-1fef475e-15e6-498b-bce1-4cdff2987ee5.png)

**Comment by grgivs** [comment] 2021-11-20 09:48
It was quite simple to do so before the UI revamp. Seems like they moved it to the new Preferences.
1. Go to Preferences
2. Select the General menu on the left side.
3. Click on Advanced Settings, it will open a drop-down menu
4. At the bottom you can find the url input box.

**Comment by aadilayub** [comment] 2021-11-20 16:37
I tried adding it there and pressing "Install" -> "Proceed to install", and nothing happens.

https://raw.githubusercontent.com/kylejbrk/standard-notes-open-extended/gh-pages/index.json

I think the field is for installing specific extensions and not adding third party extension repos.

**Comment by kylejbrk** [comment] 2021-11-21 19:03
@aadilayub  Are you pasting it in the box that says "Activate Offline Subscription"?

Also are you using the desktop app or web app? Currently web app is not supported.

**Comment by kylejbrk** [comment] 2021-11-21 19:09
Looks like extension repos may have been removed

https://github.com/standardnotes/web/issues/713#issuecomment-956263088

**Comment by ashutoshsaboo** [comment] 2021-11-21 19:10
Was facing the same issue @kylejbrk, sorry if a dumb question - where is this 'activate offline subscription' option on the new SN UI? Could you share a screenshot if possible? I'm on SN 3.9.4 on mac desktop app.

**Comment by kylejbrk** [comment] 2021-11-21 19:14
@ashutoshsaboo 
Preferences > General > Advanced Settings 

![image](https://user-images.githubusercontent.com/35229089/142775783-1d298de1-7db1-4d3e-ae43-b331800d7241.png)

**Comment by ashutoshsaboo** [comment] 2021-11-21 19:18
Umm very weird, the screenshot that you pasted i can see only on https://app.standardnotes.org/ (which is the old one). In-fact for their com domain - https://app.standardnotes.com/ only the latter is shown (install custom extension option) without the first option. And same is the behaviour for the mac app version that i mentioned. 

Which version of app are you using, from where you took this screenshot?

**Comment by kylejbrk** [comment] 2021-11-21 19:22
I had no idea there are two domains.
Both show the same thing on my end. Is it possible you are signed in to one but not the other? When im signed I also dont see it but instead see all my installed extensions.

Regardless, I am honestly not sure of the function of the Offline subscription box and cant seem to install the repo that way either.

**Comment by ashutoshsaboo** [comment] 2021-11-21 19:26
Yeah the new UI seems to be non-intuitive. only logical reason i could think of this is maybe we have already activated our offline subscriptions earlier (by pasting this repo's extension code earlier so). 
Alas, there's still no mention of any such past activation of offline extensions which is why the option isn't being shown. 🤷‍♂️

**Comment by kylejbrk** [comment] 2021-11-21 19:37
Definitely unfortunate news.
In the meantime, you can still install extensions individually from the repo. 

1. Go to: https://raw.githubusercontent.com/kylejbrk/standard-notes-open-extended/gh-pages/index.json
2. Find the extension you want to install from the list
3. Copy the value from "latest_url"
4. Paste url into "Install Custom Extension" in Preferences > General > Advanced Settings (Desktop Only)
5. Rinse and repeat for all desired extensions

If this is how it will be going forward, I could possibly rework this repo so its more intuitive for the install process. But will wait to see if more info comes to light.

**Comment by julianfairfax** [comment] 2021-11-22 16:31
I think this is because of the 2fa manager, which is now not able to used in this way.

**Comment by julianfairfax** [comment] 2021-11-22 19:22
The mobile app also doesn't accept this anymore either since you have to install the extensions manually. No more tokenvault for me.

**Comment by kylejbrk** [comment] 2021-11-22 19:25
> The mobile app also doesn't accept this anymore either since you have to install the extensions manually. No more tokenvault for me.

Tokenvault is working for me on iPhone. although i already had it installed on my account. 
I don't see why it wouldn't work though since it's just an editor.

Also MFA is still working for me as well via the extension.

**Comment by julianfairfax** [comment] 2021-11-22 19:28
Both of those things are probably only because you had it before and it assumes you have paid then. If I, with my new account, add the tokenvault extension, it doesn't work on my phone, saying I haven't paid. And if I had the 2fa manger extension, nothing happens and the settings still say I haven't paid.

**Comment by spazzanator** [comment] 2021-11-29 04:55
Can confirm today that the same thing is happening only on the web versions (both the live and selfhosted), extensions are stating that you have no active subscription and are in read only mode until that is rectified.
The desktop app allows you to use any of the extensions

**Comment by VPaulV** [comment] 2021-12-04 21:57
https://github.com/standardnotes/desktop/issues/789#issuecomment-984716573 I think here is the answer

**Comment by julianfairfax** [comment] 2021-12-04 22:11
> [standardnotes/desktop#789 (comment)](https://github.com/standardnotes/desktop/issues/789#issuecomment-984716573) I think here is the answer

We'd have to rebuild them all to fix that. Just changing the identifiers is not enough

**Comment by julianfairfax** [comment] 2021-12-04 22:18
> [standardnotes/desktop#789 (comment)](https://github.com/standardnotes/desktop/issues/789#issuecomment-984716573) I think here is the answer

This could be fixed by hosting them all ourselves. This repo works by downloading them from the official repo, which has the official identifier and so doesn't work. And we can't download one folder so downloading them from this repo itself wouldn't work. If you use the method from above to install an individual extension like the 2fa manger, you can then go to the Standard Notes config folder, then Extensions, and then modify the identifier in the dist.js and dist.min.js files in the extension's folder.

**Comment by julianfairfax** [comment] 2021-12-04 22:55
And at least with the 2fa manager, the identifier has to be changed on the repo too so that it's mapped in mapping.json when downloading since Standard Notes will download the map the 2fa manager itself and you can't modify the directly or the mapping file. So if anyone wants to use it, follow the instructions above but from this url: https://raw.githubusercontent.com/julianfairfax/standard-notes-open-extended/gh-pages/index.json and then replace `org.` with `com.` like I did on my fork. You don't have to use that as your identifier, but since it's download and mapped with that identifier, it'll make things easier for you to remember. I changed this it's also easy to remember but since they actually changed their own domain recently from .org to .com, maybe the official identifiers will actually be com. in the future.

**Comment by julianfairfax** [comment] 2021-12-04 23:03
Unfortunately even if I do both of these things, the mobile app still doesn't like it since I don't actually have extended.

**Comment by julianfairfax** [comment] 2021-12-04 23:14
I have a direct link for the 2fa manager now that works since I'm hosting it myself (https://raw.githubusercontent.com/julianfairfax/standard-notes-open-extended/gh-pages/mfa-link/index.json). Unfortunately, even using my url (https://raw.githubusercontent.com/julianfairfax/standard-notes-open-extended/gh-pages/index.json) for importing everything still doesn't work. I will try to figure out where it's going wrong.

**Comment by julianfairfax** [comment] 2021-12-04 23:50
> Unfortunately even if I do both of these things, the mobile app still doesn't like it since I don't actually have extended.

I haven't been able to resolve this issue with TokenVault, and either way I'm not going to host every extension by myself even if it works with others. So what I've done is got 2fa to work and in a convenient manor, but apart from that everything else is still desktop-only for now. Progress, or lack thereof is all here: https://github.com/julianfairfax/standard-notes-open-extended/tree/gh-pages.

And for whatever reason, trying to import everything still doesn't work, even with my changes. I don't know how to fix that.

**Comment by VPaulV** [comment] 2021-12-05 00:38
I don't use mobile app, so cannot suggest anything unfortunately, but for those who is using web.app and desktop application u can build client yourself and the license will work just as before. You only need to revert this 2 commits:
https://github.com/standardnotes/web/commit/cf3664751f5530ad96fedb6404a5b2357da7567b
https://github.com/standardnotes/web/commit/6f3a749e52a91dd9966fc52ac0247c5cd6575d6c

In 6f3a749e u can keep 3.9.5 package version and 2.18.2 snjs

So far the solution is temporary, I guess they will break it even more later.

**Comment by julianfairfax** [comment] 2021-12-05 00:49
Well I've got 2fa so I'm happy

**Comment by kylejbrk** [comment] 2021-12-05 04:17
Okay so Im wondering if taking the identifier out from the all JSONs that will fix the issue for importing individual extensions.

For example this the same exact bold editor all I did was remove the identifier. Seems to work fine.
https://listed.to/p/CkPVliFAPx

**Comment by kylejbrk** [comment] 2021-12-05 04:20
2FA working as well

https://listed.to/p/b3ccEw83Tv

**Comment by julianfairfax** [comment] 2021-12-05 09:23
> Okay so Im wondering if taking the identifier out from the all JSONs that will fix the issue for importing individual extensions.
> 
> For example this the same exact bold editor all I did was remove the identifier. Seems to work fine. https://listed.to/p/CkPVliFAPx

There never was an issue importing individual extensions except the 2fa manger, and except that it doesn't work on mobile.

> 2FA working as well
> 
> https://listed.to/p/b3ccEw83Tv

And this only works because I made changes to the actual extension download. Removing the identifier or not doesn't change anything.

**Comment by VPaulV** [comment] 2021-12-05 09:28
> There never was an issue importing individual extensions except the 2fa manger, and except that it doesn't work on mobile.

For me actually have of the plugins didn't work even tho I have paid subscription, so self hosted for myself and fixed everything

**Comment by kylejbrk** [comment] 2021-12-05 22:39
If you leave the identifier in, the plugins will not work. For example, if you try the bold editor with the identifier it will be in read only mode and ask you to upgrade to extended. Taking it out fixes this.

For 2FA you are correct. I mistakenly copied your index.json instead of my own. The identifier alone will not fix that.

**Comment by kylejbrk** [comment] 2021-12-05 23:01
Okay so @julianfairfax looking through your commits it seems you just changed the domain from .org to .com and that fixed? Confirmed this myself so went ahead and pushed: 7ef07cfdab0bd07c393d96773edc2488b85cadef to change all the identifiers.

So everything should work assuming you install extensions individually.

P.S. 2FA works as well. But after you install it you need to close out of the settings and reopen it for it to appear.

**Comment by kylejbrk** [comment] 2021-12-05 23:13
Not sure actually if the .org/.com part actually mattered. I think the only thing that mattered is that all the index.json don't match the identifier in the official repos. That seems to line up with what the dev was saying in the comment.

But anyway its working for now. Will keep this open and may have to change the instructions so people will know how to use this repo going forward.

**Comment by julianfairfax** [comment] 2021-12-06 05:13
> If you leave the identifier in, the plugins will not work. For example, if you try the bold editor with the identifier it will be in read only mode and ask you to upgrade to extended. Taking it out fixes this.
> 
> For 2FA you are correct. I mistakenly copied your index.json instead of my own. The identifier alone will not fix that.

Oh ok so that's what fixes it. It doesn't matter to me though since the only editor I wanted to use is TokenVault which is public-source now meaning we're not permitted to do this.



> Not sure actually if the .org/.com part actually mattered. I think the only thing that mattered is that all the index.json don't match the identifier in the official repos. That seems to line up with what the dev was saying in the comment.
> 
> But anyway its working for now. Will keep this open and may have to change the instructions so people will know how to use this repo going forward.

It doesn't. You can change it to anything, or apparently remove it.

**Comment by julianfairfax** [comment] 2021-12-06 05:20
What's weird is I tried what you did both with the 2fa manager only changing the identifier and changing the identifier for tokenvault but it didn't work. Maybe it's because you also changed it in the master branch? In any case, yay!

**Comment by ashutoshsaboo** [comment] 2021-12-06 06:11
> There never was an issue importing individual extensions except the 2fa manger, and except that it doesn't work on mobile.

Is this change with just changing the identifiers in json now working on mobile as well, without rebuilding the source that you had to do for mfa-link @julianfairfax ? Did you get a chance to check that? @kylejbrk

**Comment by julianfairfax** [comment] 2021-12-06 06:12
It should work on mobile, yes. And the source isn't rebuilt here.

**Comment by kylejbrk** [comment] 2021-12-06 15:47
@ashutoshsaboo I did not make a new account to test 2fa on mobile.
Is it still not working for you? Does it work on the desktop client?

**Comment by ashutoshsaboo** [comment] 2021-12-06 16:38
I just figured my old 2fa installation was already working even on mobile; so didn't mind bothering the existing setup! i also don't have a new mobile account. 

For you in the settings -> security tab - does it also show the below message with the identifier change that was made above @kylejbrk @julianfairfax ? Or does it show anything else other than this?
```
Two-factor authentication not available. A paid subscription plan is required to enable 2FA. 
```  
Currently, 2FA is working for me despite showing the above message on my existing extension installation.

**Comment by pluja** [comment] 2021-12-24 12:59
Is there any solution to this yet? I can't seem to install the folders component, and the same happens with others :(

**Comment by kylejbrk** [comment] 2022-10-05 21:28
Made some pretty major changes to this project. 

You can now activate all the extensions individually by going here: https://github.com/kylejbrk/standard-notes-open-extended/tree/gh-pages#readme

This pulls from the updated extension sources and will still check for updates daily.

**Closed by kylejbrk** 2022-10-05 21:28 UTC
